name: Build and Package Application

on:
  push:
    branches:
      - main  # Esegui il workflow quando si pusha su branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usa l'ultima versione di Ubuntu come ambiente di build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.3'  # Sostituisci con la tua versione di Python (es. 3.8)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: dist/main  # Sostituisci con il percorso dell'eseguibile generato da PyInstaller
